# Generated by Django 4.2.7 on 2023-11-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50)),
                ('question_zip', models.FileField(blank=True, upload_to='files/')),
                ('issolved', models.BooleanField(default=False)),
                ('for_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.student')),
            ],
        ),
        migrations.CreateModel(
            name='ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=50)),
                ('answer_zip', models.FileField(blank=True, upload_to='files/')),
                ('for_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.test')),
                ('for_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.student')),
            ],
        ),
    ]
